
import React from 'react';
import { Link } from "react-router-dom";
import { ChevronLeft, RefreshCw } from "lucide-react";
import { BottomNav } from "@/components/BottomNav";
import { Button } from "@/components/ui/button";
import { StrategiesComparisonTable } from '@/components/strategy/StrategiesComparisonTable';
import { useAllStrategiesMetrics } from '@/hooks/strategy/useAllStrategiesMetrics';
import { toast } from 'sonner';
import Header from "@/components/Header";

const StrategiesComparison = () => {
  const { strategies, loading, error, refreshData } = useAllStrategiesMetrics();

  const handleRefresh = () => {
    refreshData();
    toast.success('Strategy metrics refreshed');
  };

  return (
    <div className="bg-charcoalPrimary min-h-screen">
      <Header />
      
      <main className="pt-16 pb-20 px-4">
        <div className="flex items-center gap-2 mb-2">
          <Link to="/dashboard" className="text-charcoalTextSecondary hover:text-white transition-colors">
            <ChevronLeft className="h-5 w-5" />
          </Link>
          <h1 className="text-xl font-bold text-white">Strategies Comparison</h1>
        </div>

        <div className="mt-4 mb-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-lg font-medium text-white">Strategy Performance Metrics</h2>
            <Button 
              variant="outline" 
              size="sm" 
              onClick={handleRefresh}
              className="flex items-center gap-1 border-gray-700 bg-charcoalSecondary/30 text-charcoalTextSecondary hover:bg-charcoalSecondary/50 hover:text-white"
            >
              <RefreshCw className="h-4 w-4" />
              Refresh
            </Button>
          </div>
          <p className="text-charcoalTextSecondary mb-6">
            Compare the performance metrics of all available trading strategies
          </p>
        </div>

        {error ? (
          <div className="p-4 border border-red-500/30 bg-red-900/10 rounded-lg text-red-300 mb-6">
            Error loading metrics: {error}
          </div>
        ) : (
          <StrategiesComparisonTable strategies={strategies} loading={loading} />
        )}

        <div className="mt-8 p-4 bg-charcoalSecondary/30 rounded-xl border border-gray-700/50 shadow-lg">
          <h3 className="text-lg font-medium text-white mb-3">About the Metrics</h3>
          <div className="space-y-3">
            <div>
              <p className="text-sm font-medium text-charcoalTextPrimary">Overall Profit</p>
              <p className="text-xs text-charcoalTextSecondary">Total profit generated by the strategy</p>
            </div>
            <div>
              <p className="text-sm font-medium text-charcoalTextPrimary">Win %</p>
              <p className="text-xs text-charcoalTextSecondary">Percentage of trades that resulted in profit</p>
            </div>
            <div>
              <p className="text-sm font-medium text-charcoalTextPrimary">Max Drawdown</p>
              <p className="text-xs text-charcoalTextSecondary">Largest peak-to-trough decline in the strategy's performance</p>
            </div>
            <div>
              <p className="text-sm font-medium text-charcoalTextPrimary">Reward/Risk</p>
              <p className="text-xs text-charcoalTextSecondary">Ratio of average profit to average loss</p>
            </div>
            <div>
              <p className="text-sm font-medium text-charcoalTextPrimary">Avg Profit/Trade</p>
              <p className="text-xs text-charcoalTextSecondary">Average profit generated per trade</p>
            </div>
          </div>
        </div>
      </main>
      
      <BottomNav />
    </div>
  );
};

export default StrategiesComparison;
